### PR TITLE
MNT: rerender

### LINKED ISSUE #33: @conda-forge-admin please rerender
@conda-forge-admin please rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #33.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #33

### CODE REVIEW

**Comment by ocefpaf** [comment]
@beckermr the error persistes with the new re-rendered version.

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=181627&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412&l=2001

It says the package already exists on cf-staging but it does not make it to the main channel.

**Comment by beckermr** [comment]
the latest commit on master never ran CI

**Comment by beckermr** [comment]
I just pushed an empty commit to master to run it

**Comment by beckermr** [comment]
the messages in the PR job don't mean anything since those jobs don't upload anywhere

**Comment by beckermr** [comment]
Alright. Now that the commit on master is actually running this works.

**Pull request merged**
