### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by jdhughes-dev**

### CODE REVIEW

**Comment by jdhughes-dev** [comment]
There is an issue with enum34. It is only needed for python 2.7. Not sure how to do this conditional install on conda-forge.

**Comment by ocefpaf** [comment]
> There is an issue with enum34. It is only needed for python 2.7. Not sure how to do this conditional install on conda-forge.

You have to add `#  [py27]` selector in from of it.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by jdhughes-dev** [comment]
Ok. Thanks for making the change.

**Review by ocefpaf — APPROVED** [review]
Should be good to go. Feel free to merge when the CIs are green. (I am without my laptop and made the changes using my cell phone so there may be a typo/mistake somewhere.)

**Comment by ocefpaf** [comment]
Thanks @jdhughes-usgs!

**Pull request merged**
