### PR TITLE
update to v3.2.12

### PR DESCRIPTION
**Pull request by jdhughes-dev**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jdhughes-dev** [comment]
How can I fix the flopy-feedstock check failure?

**Comment by ocefpaf** [comment]
> How can I fix the flopy-feedstock check failure?

Looks like a problem with Azure. Let's try to close and re-open to toggle the CIs.

**Comment by jdhughes-dev** [comment]
@ocefpaf any idea why the linux, osx, and win-32 builds aren't available for v3.2.12 yet?

**Comment by ocefpaf** [comment]
> @ocefpaf any idea why the linux, osx, and win-32 builds aren't available for v3.2.12 yet?

`conda-forge` stopped building `win-32` a few years ago. I'm checking if the Azure outage affect the upload on Linux and macOS.

**Comment by ocefpaf** [comment]
Indeed the CIs never started on `master`. I just restart them with a force push and you can see the results in https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=39295

**Comment by jdhughes-dev** [comment]
@ocefpaf Thanks.

**Pull request merged**
