### PR TITLE
flopy version 3.3.1

### PR DESCRIPTION
**Pull request by jdhughes-dev**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jdhughes-dev** [comment]
@ocefpaf any idea how long it will be before version 3.3.1 shows up on conda-forge? Is these something else that needs to be done?

**Comment by ocefpaf** [comment]
It usually takes ~1 hour for the cdn to sync. But it looks like the package never made into the channel. Probably a CI issue in master. I'll take a look tomorrow morning.

**Comment by ocefpaf** [comment]
The CIs passed but for some odd reason version 3.3.1 is not in the channel yet: https://anaconda.org/conda-forge/flopy/files

@beckermr I'm seeing:

```
Using STAGING_BINSTAR_TOKEN for anaconda.org uploads to cf-staging.
Distribution D:\bld\win-64\flopy-3.3.1-py38h23f93f0_0.tar.bz2 already exists on cf-staging. Waiting another 15 seconds to try uploading again.
Distribution D:\bld\win-64\flopy-3.3.1-py38h23f93f0_0.tar.bz2 already exists on cf-staging. Waiting another 30 seconds to try uploading again.
Distribution D:\bld\win-64\flopy-3.3.1-py38h23f93f0_0.tar.bz2 already exists on cf-staging. Waiting another 45 seconds to try uploading again.
Distribution D:\bld\win-64\flopy-3.3.1-py38h23f93f0_0.tar.bz2 already exists on cf-staging. Waiting another 60 seconds to try uploading again.
Distribution D:\bld\win-64\flopy-3.3.1-py38h23f93f0_0.tar.bz2 already exists on cf-staging. Waiting another 75 seconds to try uploading again.
WARNING: Distribution D:\bld\win-64\flopy-3.3.1-py38h23f93f0_0.tar.bz2 already existed in cf-staging for a while. Deleting and re-uploading.
ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)
copy results:
{}
```

Not sure how to fix that.

**Comment by beckermr** [comment]
Try to rerender using the admin service. If that doesn’t work let me know.

**Comment by ocefpaf** [comment]
Ah. This was a user PR and not the bot's. I assumed it was updated.

**Pull request merged**
